import assert from 'node:assert/strict';
import { readdir,readFile } from 'node:fs/promises';
import { DatabaseSync } from 'node:sqlite';
import test from 'node:test';
import { handleIntegration } from '../lib/integration.ts';
const config={token:'test-credential-32-characters-minimum-only',subject:'swarm-test',scopes:['organizations','contacts','deals','tasks','documents'].flatMap(r=>[`${r}:read`,`${r}:write`]).join(',')};
function request(body,key='test-operation-0001',token=config.token){return new Request('https://crm.example/api/integrations/v1/commands',{method:'POST',headers:{authorization:`Bearer ${token}`,'idempotency-key':key,'content-type':'application/json'},body:JSON.stringify(body)});}
async function setup(t){const sql=new DatabaseSync(':memory:');t.after(()=>sql.close());sql.exec('PRAGMA foreign_keys=ON');for(const file of (await readdir(new URL('../drizzle/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())sql.exec(await readFile(new URL(`../drizzle/${file}`,import.meta.url),'utf8'));const prepared=(q,b=[])=>({bind(...v){return prepared(q,v)},async first(){return sql.prepare(q).get(...b)??null},async all(){return {success:true,results:sql.prepare(q).all(...b)}},async run(){if(/^\s*SELECT/i.test(q))return {success:true,results:sql.prepare(q).all(...b),meta:{changes:0}};const r=sql.prepare(q).run(...b);return{success:true,meta:{changes:Number(r.changes)}}}});const db={prepare:prepared,async batch(statements){sql.exec('BEGIN');try{const r=[];for(const s of statements)r.push(await s.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db,async call(body,key){const response=await handleIntegration(request(body,key),db,config);return{status:response.status,body:await response.json(),headers:response.headers}}};}

test('service authentication and resource scopes fail closed, operator headers confer no authority',async t=>{const {db}=await setup(t);let r=await handleIntegration(request({operation:'organizations.search'}),db,{...config,token:null});assert.equal(r.status,503);r=await handleIntegration(request({operation:'organizations.search'},undefined,'wrong'),db,config);assert.equal(r.status,401);r=await handleIntegration(request({operation:'organizations.create',data:{name:'x',sourceLabel:'test'}}),db,{...config,scopes:'organizations:read'});assert.equal(r.status,403);const req=request({operation:'organizations.search'},undefined,'wrong');req.headers.set('oai-authenticated-user-email','owner@27pm.org');assert.equal((await handleIntegration(req,db,config)).status,401);});

test('organization commit is atomic, immutable replay survives later edits, mismatched reuse conflicts',async t=>{const {sql,call}=await setup(t);const command={operation:'organizations.create',data:{name:'Integration test',sourceLabel:'Test fixture'}};const first=await call(command);assert.equal(first.status,201,JSON.stringify(first.body));assert.equal(first.body.persisted,true);const id=first.body.item.id;assert.equal(sql.prepare('SELECT name FROM organizations WHERE id=?').get(id).name,'Integration test');const updated=await call({operation:'organizations.update',id,data:{name:'Edited',sourceLabel:'Test fixture'}},'different-key-001');assert.equal(updated.status,200,JSON.stringify(updated.body));const replay=await call(command);assert.equal(replay.headers.get('idempotency-replayed'),'true');assert.deepEqual(replay.body,first.body);assert.equal((await call({...command,data:{...command.data,name:'conflicting'}})).status,409);assert.equal(sql.prepare("SELECT COUNT(*) n FROM integration_operations").get().n,2);assert.equal(sql.prepare("SELECT COUNT(*) n FROM audit_entries WHERE action='integration.create'").get().n,1);assert.equal((await call({operation:'organizations.read',id})).body.item.name,'Edited');assert.equal((await call({operation:'organizations.search',query:'Edited'})).body.items.length,1);});

test('receipt persistence failure rolls back entity, related records, audit and key reservation',async t=>{const {sql,call}=await setup(t);sql.exec("CREATE TRIGGER receipt_failure BEFORE UPDATE OF response_json ON integration_operations BEGIN SELECT RAISE(ABORT,'receipt_failure'); END");const result=await call({operation:'organizations.create',data:{name:'Must roll back',sourceLabel:'Test'}});assert.equal(result.status,503);assert.equal(sql.prepare("SELECT count(*) n FROM organizations WHERE name='Must roll back'").get().n,0);assert.equal(sql.prepare('SELECT count(*) n FROM integration_operations').get().n,0);assert.equal(sql.prepare("SELECT count(*) n FROM audit_entries WHERE actor_email='integration:swarm-test'").get().n,0);});

test('real deal/task/document lifecycle persists; outbound and arbitrary fields are refused',async t=>{const {sql,call}=await setup(t);const org=await call({operation:'organizations.create',data:{name:'Lifecycle',sourceLabel:'Test'}});const deal=await call({operation:'deals.create',data:{organizationId:org.body.item.id,projectType:'Site',estimatedValueCents:50000}},'deal-create-0001');assert.equal(deal.status,201,JSON.stringify(deal.body));const task=await call({operation:'tasks.create',data:{dealId:deal.body.item.id,title:'Prepare estimate'}},'task-create-0001');assert.equal(task.status,201,JSON.stringify(task.body));assert.equal(task.body.item.contactAction,0);const done=await call({operation:'tasks.update',id:task.body.item.id,data:{status:'done'}},'task-update-0001');assert.equal(done.status,200);assert.ok(done.body.item.completedAt);const doc=await call({operation:'documents.create',data:{dealId:deal.body.item.id,title:'Prepared estimate',content:'# Estimate\nDraft only.'}},'document-create-0001');assert.equal(doc.status,201,JSON.stringify(doc.body));assert.equal(doc.body.item.status,'prepared');assert.equal((await call({operation:'documents.update',id:doc.body.item.id,data:{content:'Revised draft'}},'document-update-0001')).body.item.content,'Revised draft');assert.equal((await call({operation:'tasks.create',data:{dealId:deal.body.item.id,title:'Mail',contactAction:true}},'task-refuse-0001')).status,400);assert.equal((await call({operation:'messages.send',data:{}},'mail-refuse-0001')).status,400);assert.equal(sql.prepare('SELECT count(*) n FROM messages WHERE direction=\'outbound\'').get().n,0);assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);});

const contactData=organizationId=>({organizationId,name:'Test contact',email:'integration@example.com',role:'Manager',sourceLabel:'User supplied',sourceUrl:'https://example.com/contact',sourceDate:'2026-08-29',provenanceType:'first_party_inbound',evidenceRef:'test-source',lawfulBasis:'none',roleRelevance:'relevant',roleRelevanceDetail:'Project coordinator',personalDataCategory:'work_contact',qualificationMode:'assisted',dnclStatus:'not_checked',emailStatus:'unknown',validated:true});
test('contact services preserve source/compliance requirements and suppression locks',async t=>{const {call}=await setup(t);const org=await call({operation:'organizations.create',data:{name:'Contacts test',sourceLabel:'Test'}});const data=contactData(org.body.item.id);const created=await call({operation:'contacts.create',data},'contact-create-0001');assert.equal(created.status,201,JSON.stringify(created.body));const id=created.body.item.id;const blocked=await call({operation:'contacts.update',id,data:{...data,doNotContact:true}},'contact-update-0001');assert.equal(blocked.status,200,JSON.stringify(blocked.body));assert.equal(blocked.body.item.doNotContact,1);assert.equal((await call({operation:'contacts.update',id,data},'contact-unblock-0001')).status,409);assert.equal((await call({operation:'contacts.create',data:{name:'missing evidence'}},'contact-invalid-0001')).status,400);});

test('state changing between preflight and transaction aborts rather than overwriting suppression',async t=>{const {db,sql,call}=await setup(t);const org=await call({operation:'organizations.create',data:{name:'Race',sourceLabel:'Test'}});const data=contactData(org.body.item.id);const c=await call({operation:'contacts.create',data},'race-contact-001');const originalBatch=db.batch;db.batch=async statements=>{sql.prepare('UPDATE contacts SET do_not_contact=1 WHERE id=?').run(c.body.item.id);db.batch=originalBatch;return originalBatch(statements)};const r=await handleIntegration(request({operation:'contacts.update',id:c.body.item.id,data:{...data,name:'Stale edit'}},'race-update-0001'),db,config);assert.equal(r.status,409);assert.equal(sql.prepare('SELECT display_name FROM contacts WHERE id=?').get(c.body.item.id).display_name,'Test contact');});

test('concurrent equal idempotency keys have exactly one effect and one audit receipt',async t=>{const {call,sql}=await setup(t);const command={operation:'organizations.create',data:{name:'Concurrent unique',sourceLabel:'Test'}};const results=await Promise.all([call(command,'concurrent-key-001'),call(command,'concurrent-key-001')]);assert.ok(results.every(r=>[200,201].includes(r.status)),JSON.stringify(results.map(r=>r.body)));assert.deepEqual(results[0].body,results[1].body);assert.equal(sql.prepare("SELECT count(*) n FROM organizations WHERE name='Concurrent unique'").get().n,1);assert.equal(sql.prepare("SELECT count(*) n FROM audit_entries WHERE action='integration.create'").get().n,1);});

test('bounded inputs and internal-only read boundary',async t=>{const {db,call,sql}=await setup(t);assert.equal((await handleIntegration(request({operation:'organizations.create',data:{name:'x'.repeat(70000)}}),db,config)).status,413);assert.equal((await call({operation:'organizations.search',limit:51})).status,400);assert.equal((await call({operation:'organizations.read',id:'absent'})).status,404);const row=sql.prepare('SELECT id FROM tasks LIMIT 1').get();sql.prepare("UPDATE tasks SET contact_action=1,contact_channel='email' WHERE id=?").run(row.id);assert.equal((await call({operation:'tasks.read',id:row.id})).status,404);assert.equal((await call({operation:'tasks.update',id:row.id,data:{status:'done'}},'no-outbound-edit')).status,404);});
