import type { DashboardData } from "./crm-types";

export const emptyDashboard: DashboardData = {
  mailboxes: [
    {
      address: "bonjour@27pm.org",
      label: "Prospects et clients",
      kind: "sales",
      unreadCount: 0,
    },
    {
      address: "admin@27pm.org",
      label: "Comptes et opérations",
      kind: "operations",
      unreadCount: 0,
    },
  ],
  transportState: "configuration",
  live: false,
  conversations: [],
  organizations: [],
  contacts: [],
  deals: [],
  tasks: [],
  intakes: [],
  activities: [],
};

function demoAccount(id: string, name: string, score: number, priority: "very_high" | "high", budgetMinCents: number, budgetMaxCents: number) {
  return { id, name, website: null, sourceLabel: "Document utilisateur — cohorte initiale", sourceUrl: null, sourceDate: null, score, priority, budgetMinCents, budgetMaxCents, budgetIsHypothesis: true, ownerEmail: null, doNotContact: false, lastContactAt: null, nextFollowUpAt: null, nextStep: "Valider le compte et identifier un rôle professionnel pertinent", notes: "Hypothèse de prospection à valider; enveloppe indicative non confirmée.", contactCount: 0 };
}

export const demoDashboard: DashboardData = {
  mailboxes: [
    {
      address: "bonjour@27pm.org",
      label: "Prospects et clients",
      kind: "sales",
      unreadCount: 3,
    },
    {
      address: "admin@27pm.org",
      label: "Comptes et opérations",
      kind: "operations",
      unreadCount: 0,
    },
  ],
  transportState: "configuration",
  live: false,
  conversations: [
    {
      id: "conversation-atelier-nord",
      mailboxAddress: "bonjour@27pm.org",
      contactId: "contact-marie",
      contactName: "Marie Tremblay",
      contactEmail: "marie@ateliernord.example",
      organization: "Atelier Nord",
      subject: "Projet de site — Atelier Nord",
      preview:
        "Bonjour, nous aimerions discuter d’un nouveau site pour Atelier Nord…",
      updatedLabel: "09:24",
      unread: true,
      followUp: true,
      dealId: "deal-atelier-nord",
      messages: [
        {
          id: "message-marie-1",
          direction: "inbound",
          senderName: "Marie Tremblay",
          senderEmail: "marie@ateliernord.example",
          recipientLabel: "bonjour@27pm.org",
          sentAt: "09:24",
          sentAtIso: "2026-08-25T13:24:00.000Z",
          deliveryState: "received",
          deliveryEvents: [],
          body:
            "Bonjour,\n\nNous aimerions discuter d’un nouveau site web pour Atelier Nord. Nous avons besoin d’un site épuré, rapide et facile à mettre à jour. Auriez-vous des disponibilités pour en discuter cette semaine ?\n\nMerci,\nMarie",
        },
        {
          id: "message-27pm-1",
          direction: "outbound",
          senderName: "27PM",
          senderEmail: "bonjour@27pm.org",
          recipientLabel: "Marie Tremblay",
          sentAt: "09:35",
          sentAtIso: "2026-08-25T13:35:00.000Z",
          deliveryState: "delivered",
          deliveryEvents: [
            {
              state: "accepted",
              occurredAt: "2026-08-25T13:35:00.000Z",
              occurredLabel: "09:35:00",
            },
            {
              state: "delivered",
              occurredAt: "2026-08-25T13:35:04.000Z",
              occurredLabel: "09:35:04",
            },
          ],
          body:
            "Bonjour Marie,\n\nMerci pour votre message. Avec plaisir pour en discuter. Seriez-vous disponible jeudi ou vendredi en avant-midi ?\n\nAu plaisir,\nPhilippe",
        },
      ],
    },
    {
      id: "conversation-gagnon",
      mailboxAddress: "bonjour@27pm.org",
      contactId: "contact-simon",
      contactName: "Simon Gagnon",
      contactEmail: "simon@gagnon.example",
      organization: "Gagnon & associés",
      subject: "Refonte de notre portail",
      preview: "Bonjour l’équipe, nous souhaitons moderniser notre portail client…",
      updatedLabel: "Hier",
      unread: true,
      followUp: false,
      dealId: "deal-gagnon",
      messages: [
        {
          id: "message-simon-1",
          direction: "inbound",
          senderName: "Simon Gagnon",
          senderEmail: "simon@gagnon.example",
          recipientLabel: "bonjour@27pm.org",
          sentAt: "Hier",
          sentAtIso: "2026-08-24T16:00:00.000Z",
          deliveryState: "received",
          deliveryEvents: [],
          body:
            "Bonjour l’équipe,\n\nNous souhaitons moderniser notre portail client et simplifier les demandes de service.\n\nSimon",
        },
      ],
    },
    {
      id: "conversation-nadia",
      mailboxAddress: "bonjour@27pm.org",
      contactId: "contact-nadia",
      contactName: "Nadia Roy",
      contactEmail: "nadia@roy.example",
      organization: "Roy Construction",
      subject: "Application de soumission",
      preview: "Nous avons besoin d’une application sur mesure pour gérer nos demandes…",
      updatedLabel: "Hier",
      unread: true,
      followUp: true,
      dealId: "deal-nadia",
      messages: [
        {
          id: "message-nadia-1",
          direction: "inbound",
          senderName: "Nadia Roy",
          senderEmail: "nadia@roy.example",
          recipientLabel: "bonjour@27pm.org",
          sentAt: "Hier",
          sentAtIso: "2026-08-24T15:00:00.000Z",
          deliveryState: "received",
          deliveryEvents: [],
          body:
            "Bonjour,\n\nNous avons besoin d’une application sur mesure pour gérer nos demandes de soumission.\n\nNadia",
        },
      ],
    },
  ],
  organizations: [
    demoAccount("org-cohort-s-huot", "S.Huot", 96, "very_high", 2_000_000, 3_500_000),
    demoAccount("org-cohort-jamec", "JAMEC", 94, "very_high", 2_500_000, 4_000_000),
    demoAccount("org-cohort-vallee", "Vallée", 92, "high", 2_500_000, 4_000_000),
    demoAccount("org-cohort-pronovost", "Machineries Pronovost", 89, "high", 3_000_000, 5_000_000),
    demoAccount("org-cohort-gii", "Groupe Industriel Interprovincial", 83, "high", 1_200_000, 2_200_000),
  ],
  contacts: [
    {
      id: "contact-marie",
      name: "Marie Tremblay",
      email: "marie@ateliernord.example",
      phone: "",
      organization: "Atelier Nord",
      organizationId: "",
      role: "Direction",
      source: "27pm.org",
      sourceUrl: "https://27pm.org/",
      sourceDate: "2026-08-25",
      contactBasis: "inbound_request",
      roleRelevance: "relevant",
      dnclStatus: "not_applicable",
      emailStatus: "valid",
      unsubscribed: false,
      doNotCall: false,
      doNotContact: false,
      lastContactAt: "2026-08-25T13:35:00.000Z",
      nextFollowUpAt: "2026-08-28T13:00:00.000Z",
      validated: true,
      status: "Nouveau prospect",
      conversationCount: 1,
    },
    {
      id: "contact-simon",
      name: "Simon Gagnon",
      email: "simon@gagnon.example",
      phone: "",
      organization: "Gagnon & associés",
      organizationId: "",
      role: "Direction",
      source: "Référence",
      sourceUrl: "https://27pm.org/",
      sourceDate: "2026-08-24",
      contactBasis: "inbound_request",
      roleRelevance: "relevant",
      dnclStatus: "not_applicable",
      emailStatus: "valid",
      unsubscribed: false,
      doNotCall: false,
      doNotContact: false,
      lastContactAt: null,
      nextFollowUpAt: null,
      validated: true,
      status: "Prospect",
      conversationCount: 1,
    },
    {
      id: "contact-nadia",
      name: "Nadia Roy",
      email: "nadia@roy.example",
      phone: "",
      organization: "Roy Construction",
      organizationId: "",
      role: "Direction",
      source: "27pm.org",
      sourceUrl: "https://27pm.org/",
      sourceDate: "2026-08-24",
      contactBasis: "inbound_request",
      roleRelevance: "relevant",
      dnclStatus: "not_applicable",
      emailStatus: "valid",
      unsubscribed: false,
      doNotCall: false,
      doNotContact: false,
      lastContactAt: null,
      nextFollowUpAt: null,
      validated: true,
      status: "Prospect",
      conversationCount: 1,
    },
  ],
  deals: [
    {
      id: "deal-atelier-nord",
      organizationId: "",
      contactId: "contact-marie",
      conversationId: "conversation-atelier-nord",
      title: "Atelier Nord",
      contactName: "Marie Tremblay",
      organization: "Atelier Nord",
      projectType: "Site web",
      stage: "nouveau",
      source: "27pm.org",
      nextAction: "Relancer vendredi",
      nextActionDate: "2026-08-28",
      note: "Clarifier le contenu, le calendrier et l’autonomie souhaitée.",
      interactions: [],
    },
    {
      id: "deal-gagnon",
      organizationId: "",
      contactId: "contact-simon",
      conversationId: "conversation-gagnon",
      title: "Portail client Gagnon",
      contactName: "Simon Gagnon",
      organization: "Gagnon & associés",
      projectType: "Application",
      stage: "qualifie",
      source: "Référence",
      nextAction: "Cadrage mardi",
      nextActionDate: "2026-09-01",
      note: "Cartographier les demandes actuelles et les rôles utilisateurs.",
      interactions: [],
    },
    {
      id: "deal-nadia",
      organizationId: "",
      contactId: "contact-nadia",
      conversationId: "conversation-nadia",
      title: "Soumissions Nadia Roy",
      contactName: "Nadia Roy",
      organization: "Roy Construction",
      projectType: "Produit numérique",
      stage: "proposition",
      source: "27pm.org",
      nextAction: "Préparer proposition",
      nextActionDate: "2026-08-27",
      note: "Inclure la validation mobile et l’export des dossiers.",
      interactions: [],
    },
  ],
  tasks: [
    {
      id: "task-atelier",
      title: "Relancer Atelier Nord",
      dueLabel: "Vendredi",
      dueAt: "2026-08-28T13:00:00.000Z",
      overdue: true,
      completed: false,
      dealId: "deal-atelier-nord",
    },
    {
      id: "task-gagnon",
      title: "Préparer le cadrage Gagnon",
      dueLabel: "Mardi",
      dueAt: "2026-09-01T13:00:00.000Z",
      overdue: false,
      completed: false,
      dealId: "deal-gagnon",
    },
  ],
  intakes: [],
  activities: [],
};
