const OUTREACH_ERROR_LABELS: Readonly<Record<string, string>> = {
  authentication_required: "Votre session a expiré. Reconnectez-vous avant de continuer.",
  operator_forbidden: "Votre compte n’est pas autorisé à modifier ce CRM.",
  allowlist_unconfigured: "La liste des opérateurs autorisés n’est pas configurée.",
  account_not_found: "L’entreprise demandée n’existe plus ou n’est pas accessible.",
  request_body_invalid: "La demande envoyée au CRM n’est pas valide.",
  contact_organization_invalid: "L’entreprise liée au contact n’est pas valide.",
  contact_identity_invalid: "Le nom, le rôle ou l’adresse courriel professionnelle est invalide.",
  contact_phone_invalid: "Le numéro de téléphone professionnel n’est pas valide.",
  contact_source_required: "La source, sa date, son URL et sa référence de preuve sont obligatoires.",
  contact_source_date_future: "La date de capture de la source ne peut pas être future.",
  contact_basis_required: "Choisissez un fondement LCAP, ou conservez explicitement « Aucun » pour bloquer le courriel.",
  contact_basis_proof_required: "Ajoutez une référence de preuve pour le fondement LCAP déclaré.",
  contact_basis_expiry_required: "Ajoutez la date d’expiration du fondement LCAP à durée limitée.",
  contact_basis_expiry_invalid: "La date d’expiration du fondement LCAP n’est pas valide.",
  contact_role_relevance_required: "Documentez la pertinence du rôle professionnel pour cette approche.",
  contact_privacy_classification_required: "Classez le renseignement et le mode de qualification du contact.",
  contact_status_required: "Indiquez le statut du courriel et, s’il y a lieu, du contrôle téléphonique.",
  contact_dncl_date_invalid: "La date de contrôle LNNTE n’est pas valide.",
  contact_dncl_date_future: "La date de contrôle LNNTE ne peut pas être future.",
  contact_phone_proof_required: "Ajoutez la provenance du téléphone et le fuseau du destinataire.",
  contact_dncl_proof_required: "Ajoutez la date et la référence de preuve du contrôle LNNTE.",
  contact_follow_up_invalid: "La date de prochaine relance n’est pas valide.",
  contact_validation_required: "Confirmez la vérification humaine du dossier avant de l’enregistrer.",
  contact_already_exists: "Cette adresse professionnelle existe déjà dans le CRM.",
  contact_create_failed: "Le contact n’a pas pu être créé.",
  contact_update_failed: "Le contact n’a pas pu être mis à jour.",
  contact_delete_failed: "Le contact n’a pas pu être supprimé.",
  contact_id_invalid: "L’identifiant du contact n’est pas valide.",
  contact_not_found: "Ce contact n’existe plus. Actualisez le CRM.",
  contact_or_account_not_found: "Ce contact ou son entreprise n’existe plus. Actualisez le CRM.",
  suppressed_contact_identity_locked: "Cette identité de contact est verrouillée par une suppression.",
  suppressed_contact_record_locked: "Ce contact est verrouillé et ne peut pas être réactivé.",
  linked_contact_account_locked: "Le contact est lié à un dossier et ne peut pas changer d’entreprise ici.",
  no_changes: "Aucune modification n’a été fournie.",
  strategy_organization_invalid: "L’entreprise sélectionnée n’est pas valide.",
  strategy_contact_invalid: "Le contact sélectionné n’est pas valide.",
  strategy_contact_mismatch: "Le contact sélectionné n’appartient pas à cette entreprise.",
  strategy_source_invalid: "Ajoutez une source publique valide pour cette stratégie.",
  strategy_source_date_invalid: "La date de vérification de la source n’est pas valide.",
  strategy_version_invalid: "La version du plan n’est pas valide. Actualisez le CRM.",
  strategy_version_conflict: "Le plan a changé ailleurs. Actualisez le CRM avant de réessayer.",
  strategy_completed_locked: "Ce plan terminé conserve son historique et ne peut plus être modifié.",
  strategy_contact_blocked: "Le contact sélectionné ne satisfait pas encore les contrôles requis.",
  strategy_schedule_invalid: "La date, l’heure ou le fuseau n’est pas valide.",
  strategy_content_invalid: "Complétez les champs de stratégie requis.",
  strategy_save_failed: "Le plan n’a pas pu être enregistré.",
  outreach_strategy_frozen: "Ce plan est en lecture seule. Réactivez-le avant de modifier ses étapes.",
  outreach_step_update_conflict: "L’étape a changé ailleurs. Actualisez le CRM avant de réessayer.",
  compliance_state_changed: "Le dossier de conformité a changé; l’étape reste bloquée.",
  strategy_contact_missing: "Aucun contact vérifié n’est lié à cette stratégie.",
  email_address_missing: "Aucune adresse courriel n’est enregistrée pour ce contact.",
  phone_address_missing: "Aucun numéro de téléphone n’est enregistré pour ce contact.",
  contact_compliance_missing: "La preuve du canal de contact est manquante.",
  contact_deleted: "Le contact ou son entreprise a été supprimé.",
  contact_suppressed: "Le contact ou son entreprise est sous suppression.",
  contact_unvalidated: "La validation du contact ou du canal est absente ou périmée.",
  non_work_personal_data_blocked: "Le dossier n’est pas qualifié comme contact professionnel.",
  role_relevance_unproven: "La pertinence professionnelle du rôle n’est pas démontrée.",
  automated_qualification_unapproved: "La qualification automatisée n’a pas été approuvée juridiquement.",
  email_channel_missing: "Le canal courriel documenté ne correspond pas à cette adresse.",
  email_unsubscribed: "Le destinataire s’est désabonné.",
  email_status_not_valid: "L’adresse courriel n’est pas encore validée.",
  email_suppressed: "L’adresse courriel est sous suppression.",
  email_lawful_basis_missing: "Le fondement LCAP n’est pas documenté.",
  email_basis_proof_incomplete: "La preuve du fondement LCAP est incomplète.",
  email_basis_expired: "Le fondement LCAP documenté est expiré.",
  email_basis_expiry_invalid: "La date d’expiration du fondement LCAP est invalide.",
  email_basis_expiry_required: "Une date d’expiration du fondement LCAP est requise.",
  publication_not_by_recipient_or_authorized: "La publication de l’adresse n’est pas attribuée au destinataire ou à une source autorisée.",
  publication_authority_unproven: "L’autorité de la source qui publie l’adresse n’est pas démontrée.",
  email_provenance_incomplete: "La provenance publique de l’adresse est incomplète.",
  publication_restricts_contact: "La source publique ne confirme pas l’absence de restriction de contact.",
  publication_role_relevance_missing: "La pertinence du rôle pour cette approche reste à confirmer.",
  direct_disclosure_provenance_missing: "La remise directe de l’adresse n’est pas documentée.",
  direct_disclosure_restriction_unknown: "Les restrictions liées à la remise directe de l’adresse sont inconnues.",
  direct_disclosure_relevance_missing: "La pertinence de l’adresse remise directement n’est pas documentée.",
  b2b_relationship_unproven: "La relation commerciale existante n’est pas démontrée.",
  b2b_message_relevance_missing: "La pertinence du message pour la relation commerciale n’est pas documentée.",
  sender_identity_incomplete: "L’identité complète de l’expéditeur doit être configurée.",
  sender_identity_validity_insufficient: "La preuve d’identité de l’expéditeur n’est pas valide pour toute la période requise.",
  unsubscribe_mechanism_incomplete: "Le mécanisme de désabonnement doit être configuré.",
  cross_border_efvp_unconfirmed: "L’évaluation des facteurs de vie privée transfrontalière n’est pas confirmée.",
  cross_border_contract_unconfirmed: "Les garanties contractuelles transfrontalières ne sont pas confirmées.",
  cross_border_legal_validation_unconfirmed: "La validation juridique du traitement transfrontalier n’est pas confirmée.",
  cross_border_evidence_missing: "La preuve du traitement transfrontalier est manquante.",
  phone_missing: "Aucun canal téléphonique documenté ne correspond à ce contact.",
  phone_do_not_call: "Ce numéro est sous interdiction d’appel.",
  phone_status_not_valid: "Le numéro de téléphone n’est pas validé.",
  phone_provenance_incomplete: "La provenance du numéro est incomplète.",
  phone_dncl_listed: "Le numéro figure sur la Liste nationale de numéros de télécommunication exclus.",
  phone_dncl_unverified: "Le statut LNNTE du numéro n’est pas vérifié.",
  phone_dncl_proof_incomplete: "La preuve de vérification LNNTE est incomplète.",
  phone_dncl_check_expired: "La vérification LNNTE est expirée.",
  organization_dncl_registration_unconfirmed: "L’inscription de l’organisation auprès de la LNNTE n’est pas confirmée.",
  business_number_unconfirmed: "Le numéro d’entreprise requis n’est pas confirmé.",
  caller_identity_incomplete: "L’identité et le numéro affiché de l’appelant sont incomplets.",
  prohibited_call_automation_enabled: "Une automatisation d’appel interdite n’est pas désactivée.",
  recipient_timezone_missing: "Le fuseau du destinataire est manquant.",
  outside_calling_hours: "L’heure locale du destinataire ne permet pas cet appel.",
  outreach_step_blocked: "Cette étape reste bloquée tant que les contrôles requis ne sont pas satisfaits.",
  outreach_step_id_invalid: "L’étape demandée n’est pas valide.",
  outreach_step_not_found: "Cette étape n’existe plus. Actualisez le CRM.",
  outreach_step_schedule_invalid: "La nouvelle date de l’étape n’est pas valide.",
  outreach_step_status_invalid: "Le nouvel état de l’étape n’est pas valide.",
  outreach_step_terminal_locked: "Cette étape terminée est verrouillée dans l’historique.",
  outreach_step_update_failed: "L’étape n’a pas pu être mise à jour.",
};

export function outreachErrorMessage(value: string): string {
  if (/timeout|timed out|aborted/iu.test(value)) {
    return "Le serveur n’a pas répondu dans le délai prévu. Vérifiez le CRM avant de réessayer.";
  }
  return value
    .split(",")
    .map((code) => code.trim())
    .filter(Boolean)
    .map((code) => OUTREACH_ERROR_LABELS[code] ?? code.replaceAll("_", " "))
    .join(" · ");
}

const GLOBAL_COMPLIANCE_REASONS = new Set([
  "sender_identity_incomplete",
  "sender_identity_validity_insufficient",
  "unsubscribe_mechanism_incomplete",
  "cross_border_efvp_unconfirmed",
  "cross_border_contract_unconfirmed",
  "cross_border_legal_validation_unconfirmed",
  "cross_border_evidence_missing",
  "automated_qualification_unapproved",
]);

export function isGlobalComplianceReason(code: string): boolean {
  return GLOBAL_COMPLIANCE_REASONS.has(code);
}
